 - name: 修改主机名
   hostname:
    name: "redis-{{ ansible_default_ipv4.address.split('.')[-1] }}"
 - name: Install a list of packages
   apt:
     name: "{{ packages }}"
   vars:
     packages:
     - make
     - wget
     - tcl8.5
   when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"
 - name: 复制redis安装包到目标主机
   copy:
    src: redis-3.2.12.tar.gz
    dest: /root
 - name: 解压redis安装包并编译
   shell: cd && tar -xf redis-{{ redis_version }}.tar.gz && cd redis-{{ redis_version }} && make && make install PREFIX=/usr/local
 - name: 创建redis用户组
   group:
    name: redis
    state: present 
 - name: 创建redis用户
   user: 
    name: redis
    groups: redis
    createhome: no
# Changed from createhome to create_home in version 2.5.
    shell: /sbin/nologin
 - name: 创建文件夹
   file: 
    dest: "{{ item }}"
    state: directory
   with_items: ['/opt/redis/6379','/opt/redis/6380'] 
 - name: 创建included配置文件
   file: 
    path: "/opt/redis/redis-included.conf"
    state: touch
 - name: 复制配置文件
   template:
     src: "{{item.src}}"
     dest: "{{item.dest}}"
     owner: redis
     group: redis
     backup: yes
   with_items:
     - { src: "redis-6379.conf.j2", dest: "/opt/redis/6379/redis-6379.conf"}
     - { src: "redis-6380.conf.j2", dest: "/opt/redis/6380/redis-6380.conf"}
 - name: 修改文件权限
   shell: chown -R redis:redis /opt/redis
 - name:  复制开机启动脚本
   copy: 
    src: "{{ item }}"
    dest: "/etc/init.d"
    mode: 0755
   with_items: ['redis-server-6379','redis-server-6380']
 - name: 设置开机启动软链接
   shell: /usr/sbin/update-rc.d redis-server-6379 defaults 40
 - name: 设置开机启动软链接
   shell: /usr/sbin/update-rc.d redis-server-6380 defaults 40
 - name: 启动redis服务6379
   service: name=redis-server-6379 state=started
 - name: 启动redis服务6380
   service: name=redis-server-6380 state=started
 - name: 复制通用配置文件
   copy:
    src: redis-included.conf
    dest: /opt/redis/redis-included.conf
    owner: redis
    group: redis
   notify: 
   - restart redis 6379
   - restart redis 6380
