---
- hosts: test
  user: root
  tasks:
  - name: 下发运行ansible用户家目录中公钥到目标主机指定用户家目录
    authorized_key:
        user: root
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
        state: present # present 添加 absent 删除
        exclusive: no
        manage_dir: yes
