---
- hosts: redis-cluster-hosts
  remote_user: root
  gather_facts: True
  roles:
  - role: install-redis-cluster-template
    redis_version: 4.0.10
    auth_password: rediscluster123
    ruby_version: 2.4.4
    when:
    - ansible_distribution == "Ubuntu" 
    - ansible_distribution_version == "16.04" or ansible_distribution_version == "14.04"
